name: Build Unity Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  buildAndroid:
    name: Build Android APK 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space on Runner
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Build Unity Android APK
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          unityVersion: 2022.3.20f1

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3D_Mobile_Shooter_APK
          path: build/Android/Android.apk
